# Generated by Django 3.1.7 on 2021-03-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallEndRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('end', 'End'), ('start', 'Start')], default='end', max_length=5)),
                ('timestamp', models.DateTimeField()),
                ('call_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CallStartRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('end', 'End'), ('start', 'Start')], default='start', max_length=5)),
                ('timestamp', models.DateTimeField()),
                ('call_id', models.CharField(max_length=64)),
                ('source', models.CharField(max_length=16)),
                ('destination', models.CharField(max_length=16)),
            ],
        ),
    ]
