# Generated by Django 3.1.7 on 2021-03-16 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callendrecord',
            name='call_id',
        ),
        migrations.AddField(
            model_name='callendrecord',
            name='call_start_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='calls.callstartrecord'),
            preserve_default=False,
        ),
    ]
