# Generated by Django 3.1.7 on 2021-03-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_auto_20210316_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='callendrecord',
            name='call_id',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
