# Generated by Django 3.1.7 on 2021-03-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_callendrecord_call_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callendrecord',
            name='call_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='callstartrecord',
            name='call_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
