# Generated by Django 3.1.7 on 2021-03-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_callrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='call_id',
            field=models.CharField(default=None, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CallEndRecord',
        ),
        migrations.DeleteModel(
            name='CallStartRecord',
        ),
    ]
