# Generated by Django 3.1.7 on 2021-04-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_auto_20210318_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
