# Generated by Django 3.1.7 on 2021-04-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0008_callrecord_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='duration',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('call_records', models.ManyToManyField(to='calls.CallRecord')),
            ],
        ),
    ]
