# Generated by Django 3.1.7 on 2021-04-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0009_auto_20210406_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='duration',
            field=models.DateTimeField(null=True),
        ),
    ]
