# Generated by Django 3.1.7 on 2021-04-06 14:36

from django.db import migrations, models
from datetime import timedelta


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0011_auto_20210406_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='duration',
            field=models.DurationField(default=timedelta()),
        ),
    ]
