# Generated by Django 3.1.7 on 2021-04-06 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0012_auto_20210406_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
