# Generated by Django 3.1.7 on 2021-04-06 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0014_remove_callrecord_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
