# Generated by Django 3.1.7 on 2021-04-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0015_callrecord_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='source',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
